### ISSUE TITLE
content modification

### ISSUE THREAD

**Issue by sathis0** [MicroPyramid/django-blog-it#102]
cannot modify the navigation bar brand name and also can't add navigation bar options !

**Comment by chaitu210** [comment]
@sathis0 will look into this and fix ASAP.

**Comment by sathis0** [comment]
bro brief me

my problem: I can't change the post page navigation bar brand name also
dashboard brand name

säthïs

**Comment by sathis0** [comment]
can I your WhatsApp num


säthïs

**Comment by chaitu210** [comment]
@sathis0 can you share screenshots of where you want to change the brand name.
