### ISSUE TITLE
add post access to all users

### ISSUE THREAD

**Issue by yatharthsharma** [MicroPyramid/django-blog-it#107]
Hi,

I have added the blog to my app but currently, the access to add blog is by the admin only. How do I make sure that anyone i.e all users can add blogs but the admin has the access to flag it for deletion?

thanks

**Comment by chaitu210** [comment]
@yatharthsharma we are having user roles in the models, so all the users who ever  having Author role can add post blog post.

**Comment by yatharthsharma** [comment]
yes. thanks for this
